### ISSUE TITLE
Suggestion to change `kn-service-log` to `kn-logs`

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-service-log#37]
Hello kn-service-logs team, greetings! This is not an issue but mostly to bring into a discussion a suggestion to change the name from `kn-service-log` to just `kn-logs` and some reason to consider doing it from user perspective.

- `kn service log <name>` seems a little more verbose than just `kn logs <name>`

-  A prefix could be used to indicate what logs are relate to (i.e. `service/` or `srv:`). User could do `kn logs service/myservice` or `kn logs srv:myservice`. In this case `service/` could be a default when no prefix is speficied turning UX even less verbose with `kn logs myservice`
 
- It seems there is a pattern around log related commands on CLI tools using the noun in plural (`logs`) instead of as a verb  (`log`). As example one can do `docker logs`, `kubectl logs`, `podman logs` and so on. For those who are familiar with that it seems more natural to try `kn logs` over `kn service log`

- By adding the plugin binary into `.config/kn/plugins/kn-service-log` it enables `kn service log` for usage but `log` does appears as a subcommand when using `kn service --help` and that may confuse users.

**Comment by rhuss** [comment]
In general, I like the proposal, but there are some drawbacks:

* The naming convention violates the schema that we have established for the remaining commands https://github.com/knative/client/blob/main/conventions/cli.md In general we should not be over strict here (especially not for plugins) and we already have something like `kn admin`. So in some sense, we could say "logs" is a noun :-). Ideally we would support _command links_ to have multiple entry points for commands
* We should be careful to have a smooth migration, so potentially creating a new repository and mark this one as _archived_.

**Comment by maximilien** [comment]
I don't dislike the idea of simplifying name to: `kn logs ...`

And in addition I would also simplify so that:

1. `kn logs` by itself shows logs of all services in the current namespace
2. `kn logs <name>` shows logs for objects by <name>
3. `kn logs <regex>` shows logs for all objects matching the <regex>
4. `kn logs -n <namespace>` restrict logs to objects in <namespace>
5. `kn logs -A` shows logs to objects in all namespaces

OR similar. Basically, from user's perspective `kn logs` shows all logs and arguments after that are designed to restrict and reduce logs to specific object(s).

The rationale is developers typically want to start with more logs and then refine as they identify log entries of interest.

Cc: @rhuss @dsmansk @itsmurugappan
